# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Session-Store-DBIC
version:      0.05
version_from: lib/Catalyst/Plugin/Session/Store/DBIC.pm
installdirs:  site
requires:
    Catalyst:                      5.65
    Catalyst::Exception:           0
    Catalyst::Plugin::Session:     0.08
    Catalyst::Plugin::Session::Store: 0
    Class::Data::Inheritable:      0
    DBIx::Class:                   0.05000
    FindBin:                       0
    MIME::Base64:                  0
    NEXT:                          0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
