---
abstract: 'Store your sessions via DBIx::Class'
author:
  - 'Daniel Westermann-Clark <danieltwc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-Store-DBIC
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Catalyst: 5.65
  Catalyst::Exception: 0
  Catalyst::Plugin::Session::Store::Delegate: 0.05
  Class::Accessor::Fast: 0
  DBIx::Class: 0.07000
  FindBin: 0
  MIME::Base64: 0
  MRO::Compat: 0
  Scalar::Util: 0
  Storable: 0
  Test::More: 0
  Test::Warn: 0.20
resources:
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Session-Store-DBIC/
version: 0.14
